server:
  port: 8082

aws:
  region: ${AWS_REGION:us-east-1}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.${AWS_REGION:us-east-1}.amazonaws.com/${COGNITO_USER_POOL_ID}

cognito:
  app-client-id: ${COGNITO_APP_CLIENT_ID}
  user-pool-id: ${COGNITO_USER_POOL_ID}